### PR TITLE
Update webhook docs to include DomainRegistration, DomainTransfer, DomainRenew events

### PR DESCRIPTION
**Pull request by juankuquintana**
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1662

We update the [webhook](https://developer.dnsimple.com/v2/webhooks/events/) events list to include the newly registered DomainTransfer, DomainRenew, DomainRegistration events.

Screen Shot 2023-02-27 at 14 42 35

## :shipit: Verification

- [ ] Deployed docs are updated

### CODE REVIEW

**Review by OleMchls — APPROVED** [review]
🙌

**Comment by DXTimer** [comment]
@juankuquintana the only thing missing is adding sample payloads for the events in the [webhook fixtures folder](https://github.com/dnsimple/dnsimple-developer/tree/main/fixtures/v2/webhooks).

**Comment by juankuquintana** [comment]
> @juankuquintana the only thing missing is adding sample payloads for the events in the [webhook fixtures folder](https://github.com/dnsimple/dnsimple-developer/tree/main/fixtures/v2/webhooks).

Added samples @DXTimer

**Review by DXTimer — APPROVED** [review]
Thank you!

**Pull request merged**
