### PR TITLE
Adds the rust api client to the list of api clients

### PR DESCRIPTION
**Pull request by ecomba**
Adds a link to the rust api client in the Official clients section.

### CODE REVIEW

**Review by weppos — APPROVED** [review]
👍 

FYI it looks like indentation is off by one, from the "DNSimple C# client" onwards.

Also, since we shipped and announced it, are we still in "development release"?
https://blog.dnsimple.com/2022/01/new-rust-api-client-library/
I suspect we're effectively in public beta phase. Can you confirm?

**Comment by ecomba** [comment]
> 👍
> 
> FYI it looks like indentation is off by one, from the "DNSimple C# client" onwards.
> 
> Also, since we shipped and announced it, are we still in "development release"? https://blog.dnsimple.com/2022/01/new-rust-api-client-library/ I suspect we're effectively in public beta phase. Can you confirm?

I can't see the "off by one" in the code 🤷🏼

As of the rust client I would still leave it in "_development release_" as we are overhauling the error handling currently.

**Comment by weppos** [comment]
> I can't see the "off by one" in the code 🤷🏼

Screenshot 2022-01-20 at 17 36 30

I think GitHub tricked me.

**Review by dallasread — APPROVED** [review]
Looks good to me!

**Pull request merged**
