### PR TITLE
Remove the required flag for Template's description

### PR DESCRIPTION
**Pull request by duduribeiro**
This field is not required. This commit removes the required flag from
it.

### CODE REVIEW

**Review by san983 — APPROVED** [review]

**Comment by weppos** [comment]
Please make sure to verify https://github.com/dnsimple/dnsimple-developer/blob/main/content/v2/openapi.yml as well. The OpenAPI definition is our primary source of truth.

**Comment by duduribeiro** [comment]
@weppos we do not track if the Parameter is required or not at Openapi https://github.com/dnsimple/dnsimple-developer/blob/eb5deb63d2b368a6af4b10bef2d93524049f7e3a/content/v2/openapi.yml#L4640

**Comment by weppos** [comment]
> @weppos we do not track if the Parameter is required or not at Openapi
> 
> https://github.com/dnsimple/dnsimple-developer/blob/eb5deb63d2b368a6af4b10bef2d93524049f7e3a/content/v2/openapi.yml#L4640

Do you mind to update it then? I think it would be something like that:

```diff
diff --git a/content/v2/openapi.yml b/content/v2/openapi.yml
index dddf817..470ad38 100644
--- a/content/v2/openapi.yml
+++ b/content/v2/openapi.yml
@@ -4645,15 +4645,18 @@ components:
           schema:
             type: object
             properties:
-              name:
-                type: string
               sid:
                 type: string
+              name:
+                type: string
               description:
                 type: string
+            required:
+              - sid
+              - name
             example:
-              name: Alpha
               sid: alpha
+              name: Alpha
               description: This is an Alpha template.
     TemplateRecordCreateOrUpdate:
       description: Attributes for creating a template record
```

**Comment by duduribeiro** [comment]
@weppos changed to add name and sid as required. 

Tested it and looks ok now
image

**Comment by weppos** [comment]
Awesome, thanks!

**Pull request merged**
